#:schema node_modules/wrangler/config-schema.json
name = "flux-1"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[ai]
binding = "AI"

[vars]
CLOUDFLARE_ACCOUNT_ID = "9c605e82c69beedc4ed0e9e381b012d0"
